from pydantic import BaseModel, Field

class ApartmentData(BaseModel):
    bedrooms: float = Field(..., description="Number of bedrooms")
    bathrooms: float = Field(..., description="Number of bathrooms")
    area_numeric: float = Field(..., description="Numeric area in sqm")
    latitude: float = Field(..., description="Latitude of the location")
    longitude: float = Field(..., description="Longitude of the location")
    
    property_type: str = Field(..., description="Type of property, e.g., apartment")
    city: str = Field(..., description="City where the apartment is located")
    governorate: str = Field(..., description="Governorate")
    finish_type: str = Field(..., description="Finish type, e.g., unknown")
    seller_name: str = Field(..., description="Name of the seller")
    view_type: str = Field(..., description="Type of view, e.g., panoramic")
    compound_name: str = Field(..., description="Name of the compound")
    delivery_date: float = Field(..., description="Delivery date as float (0.0 for ready)")
    seller_type: str = Field(..., description="Seller type: 'agency' or 'individual'")
    furnished: str = Field(..., description="Furnished status: 'yes', 'no', or 'unknown'")
    ownership: str = Field(..., description="Ownership status: 'primary' or 'resale'")
    payment_option: str = Field(..., description="Payment option: 'cash', 'installment', or 'cash or installment'")
    completion_status: str = Field(..., description="Completion status: 'off-plan' or 'ready'")

    Electricity_Meter: bool = Field(False, alias="Electricity Meter")
    Water_Meter: bool = Field(False, alias="Water Meter")
    Natural_Gas: bool = Field(False, alias="Natural Gas")
    Security: bool = Field(False)
    Covered_Parking: bool = Field(False, alias="Covered Parking")
    Pets_Allowed: bool = Field(False, alias="Pets Allowed")
    Landline: bool = Field(False)
    Balcony: bool = Field(False)
    Private_Garden: bool = Field(False, alias="Private Garden")
    Pool: bool = Field(False)
    Built_in_Kitchen_Appliances: bool = Field(False, alias="Built in Kitchen Appliances")
    Elevator: bool = Field(False)
    Central_AC_heating: bool = Field(False, alias="Central A/C & heating")
    Maids_Room: bool = Field(False, alias="Maids Room")
    roof: bool = Field(False)
